name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check deployed application
        uses: jtalk/url-health-check-action@v5
        with:
          url: https://fullstack-hy-cicd-flight-diaries.fly.dev/ping
